#
#  //\\   OmenMon: Hardware Monitoring & Control Utility
# //  \\  Copyright © 2023 Piotr Szczepański * License: GPL3
#     //  https://omenmon.github.io/
#
# OmenMon Release Workflow
# Triggers a build and uploads artifacts as release assets

name: "OmenMon Release"
run-name: "OmenMon Release by ${{ github.actor }}"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  call-build:
    name: "Call Build"
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      version_number: ${{ github.event.release.tag_name }}
      version_word: ${{ github.event.release.prerelease && 'Preview' || 'Release' }}

  release:
    name: "Release OmenMon"
    needs: call-build
    runs-on: ubuntu-latest

    steps:
    - id: download
      name: "Download Artifacts"
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.repository.name }}

    - name: 'List Artifacts'
      run: ls -1R ${{ steps.download.outputs.download-path }}

    - name: "Create Archive"
      run: zip -9 -r OmenMon.zip ./*

    - name: "Create Archive Comment"
      run: |
        BUILD_NUM="${{ vars.BUILD_NUMBER || '0' }}"
        TAG_VERSION="${{ github.event.release.tag_name }}"
        cat >OmenMon.zip.txt <<EOF
        @ (zip file comment below this line)
          //\\\\\\\\   OmenMon Version $TAG_VERSION-${{ github.event.release.prerelease && 'Preview' || 'Release' }}
         //  \\\\\\\\  Build $BUILD_NUM * $(date -u +"%Y-%m-%d %H:%M") UTC
             //  https://omenmon.github.io/
        EOF

    - name: "Add Comment to Archive"
      run: zipnote -b . -w OmenMon.zip < OmenMon.zip.txt

    - name: "Rename Archive for Release"
      run: mv OmenMon.zip OmenMon-${{ github.event.release.tag_name }}-${{ github.event.release.prerelease && 'Preview' || 'Release' }}.zip

    - name: "Upload OmenMon Assets"
      uses: softprops/action-gh-release@v1
      with:
        files: ./OmenMon-${{ github.event.release.tag_name }}-${{ github.event.release.prerelease && 'Preview' || 'Release' }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
